version: '2'
services:

  luigid:
    image: digits-luigi-pipeline/orchestrator:latest
    build:
      context: ./orchestrator
    command: luigid
    ports:
      - "8082:8082"
    networks:
      - digits-pipeline

  # executes and orchestrates the pipeline
  orchestrator:
    image: digits-luigi-pipeline/orchestrator:latest
    depends_on:
      - luigid
    environment:
      - PROJECT_ROOT=$PWD
      - PIPELINE_VERSION=1.0
      - ORCHESTRATOR_NETWORK=luigi_digits-pipeline
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
    networks:
      - digits-pipeline
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # Mount docker socket to run docker images inside
      - ./orchestrator:/opt/orchestrator # Mount code if needed for development
    build:
      context: ./orchestrator
    command: luigi --module pipeline TrainModel --scheduler-host luigid

networks:
    digits-pipeline:
        driver: bridge
