version: '3.3'

services:
    db:
        restart: always
        image: mysql/mysql-server:5.7.28
        container_name: mlflow_db
        expose:
            - "3306"
        networks:
            - mlnetwork
        environment:
            - MYSQL_DATABASE=db
            - MYSQL_USER=mlflow
            - MYSQL_PASSWORD=weakpassword
            - MYSQL_ROOT_PASSWORD=weakerpassword
        volumes:
            - dbdata:/var/lib/mysql

    web:
        restart: always
        build: ./docker/mlflow
        image: mlflow_server
        container_name: mlflow_server
        ports:
            - "5000:5000"
        expose:
            - "5000"
        networks:
            - mlnetwork
        environment:
            - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
            - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
            - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
        command: mlflow server --backend-store-uri mysql+pymysql://mlflow:weakpassword@db:3306/db --default-artifact-root s3://digits-recognizer-project/experiments --host 0.0.0.0 
        # command: mlflow server --backend-store-uri mysql+pymysql://mlflow:weakpassword@db:3306/db --artifacts-destination s3://digits-recognizer-project/experiments --serve-artifacts --host 0.0.0.0
        depends_on:
            - db

networks:
    mlnetwork:
        driver: bridge

volumes:
    dbdata: